import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="w-full flex justify-center mt-6">
  <ul className="flex gap-3 p-2 rounded-2xl border border-yellow-500/20 bg-black/30 backdrop-blur-xl shadow-[0_8px_32px_rgba(255,193,7,0.15)]">
    <li>
      <Link
        href="/"
        className="px-6 py-3 rounded-xl text-yellow-300 font-medium transition-all duration-300 hover:bg-yellow-400/10 hover:text-yellow-200 hover:shadow-[0_0_20px_rgba(255,193,7,0.3)]"
      >
        Users
      </Link>
    </li>

    <li>
      <Link
        href="/users/add"
        className="px-6 py-3 rounded-xl text-yellow-300 font-medium transition-all duration-300 hover:bg-yellow-400/10 hover:text-yellow-200 hover:shadow-[0_0_20px_rgba(255,193,7,0.3)]"
      >
        Add User
      </Link>
    </li>
  </ul>
</nav>
        {children}
        
      </body>
    </html>
  );
}
